# Generated by Django 6.0.6 on 2026-06-10 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='expediteur',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='utilisateur',
        ),
        migrations.AlterUniqueTogether(
            name='programmeetudes',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='programmeetudes',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='user',
        ),
        migrations.AlterField(
            model_name='utilisateurdisponibilite',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utilisateurcompetence',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annoncementorat',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utilisateurlacune',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lacunes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reponseoffre',
            name='postulant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_envoyees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='reponseoffre',
            old_name='date_response',
            new_name='date_reponse',
        ),
        migrations.AddField(
            model_name='annoncementorat',
            name='disponibilite',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='annoncementorat',
            name='nb_reponses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annoncementorat',
            name='statut',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='annoncementorat',
            name='format_propose',
            field=models.CharField(choices=[('présentiel', 'Présentiel'), ('en ligne', 'En ligne'), ('les deux', 'Les deux')], max_length=20),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('format', models.CharField(choices=[('présentiel', 'Présentiel'), ('en ligne', 'En ligne'), ('les deux', 'Les deux')], max_length=20)),
                ('statut', models.CharField(choices=[('upcoming', 'À venir'), ('done', 'Terminée'), ('cancelled', 'Annulée')], default='upcoming', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.matiere')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_mentor', to=settings.AUTH_USER_MODEL)),
                ('mentore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_mentore', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='ProgrammeEtudes',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
